name: CI


on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build Dockerfile and push image # userで外部ファイル or 定義済みの処理を実行できる。ここではリポジトリのcheckout
      run: |
        IMAGE_NAME=test_container:${{github.job}}
        docker build CustomerApi -f CustomerApi/CustomerApi/Dockerfile -t docker.pkg.github.com/${REPOSITORY_NAME,,}/${IMAGE_NAME}
        echo docker login docker.pkg.github.com --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
        docker login docker.pkg.github.com --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
        docker push docker.pkg.github.com/${REPOSITORY_NAME,,}/${IMAGE_NAME}
      env: 
        REPOSITORY_NAME: ${{ github.event.repository.name }}
